#!/usr/bin/env bash
#
# Preloads ONE tier-matched local LLM for AI mode via `ollama pull`. Replaces the
# old LM Studio bulk `lms get` download. Image-generation models (FLUX/SDXL) are
# NOT here — those run in ComfyUI, see 04-download-image-models.sh.
#
# By default it pulls the *coding* model for the active hardware TIER — a single
# ~4-5GB 7B on a laptop, not 150GB of every model. Switching to another use-case
# later (`distro-ai-model use <case>`) pulls that model on demand, so there's no
# need to download them all up front.
#
# The tier comes from --tier, else $REFRACT_AI_TIER, else ~/.config/refract-ai/tier
# (written by distro-ai-detect-tier), else 'max'.
#
# Usage:
#   ./02-preload-models.sh                     # coding model for the active tier
#   ./02-preload-models.sh --tier entry        # coding model for the entry tier
#   ./02-preload-models.sh day-to-day          # a different use-case, active tier
#   ./02-preload-models.sh --tier high coding  # coding model for the high tier
#
# Use-cases: coding cad day-to-day know-it-all uncensored assistant vision
#            (image generation is ComfyUI — see distro-ai-image, not here).

set -euo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/refract-ai"

# --tier <t> may lead the args; otherwise fall back to env/config/default.
TIER=""
if [ "${1:-}" = "--tier" ]; then
    TIER="${2:-}"
    [ -n "$TIER" ] || { echo "--tier requires a tier name (cpu entry mid high max ultra)." >&2; exit 1; }
    shift 2   # safe: a non-empty $2 guarantees $# >= 2, so this never aborts under set -e
fi
[ -n "$TIER" ] || TIER="${REFRACT_AI_TIER:-$(cat "$CONFIG_HOME/tier" 2>/dev/null || echo max)}"
case "$TIER" in
    cpu|entry|mid|high|max|ultra) ;;
    *) echo "Unknown tier '$TIER' (cpu entry mid high max ultra)." >&2; exit 1 ;;
esac

# Effective (pooled) VRAM in MiB — the SAME input distro-ai-model gates its tag
# selection on (written by distro-ai-detect-tier; env overrides). We must read it
# identically or we preload a tag `distro-ai-model use` would then reject and
# re-download. 0/empty = unknown -> no gating, matching distro-ai-model.
VRAM_MIB="${REFRACT_VRAM_MIB:-$(cat "$CONFIG_HOME/vram_mib" 2>/dev/null || echo 0)}"
[[ "$VRAM_MIB" =~ ^[0-9]+$ ]] || VRAM_MIB=0

# Laptop power PROFILE — the SAME source distro-ai-model reads. Only 'efficiency'
# changes the pick: distro-ai-model then loads the LIGHTEST model the use-case
# offers (ranked by min_vram_gb), not the tier's default class. If we ignore it
# here, an efficiency laptop preloads the heavier tier tag and re-downloads on the
# first `distro-ai-model use` — so mirror it below. balance/power keep the tier
# order (see distro-ai-model's resolver: profile moves the pick WITHIN the tier).
PROFILE="${REFRACT_AI_PROFILE:-$(cat "$CONFIG_HOME/profile" 2>/dev/null || echo balance)}"

# The use-case to preload (default: coding) — one positional arg after --tier.
USECASE="${1:-coding}"
case "$USECASE" in
    coding|cad|day-to-day|know-it-all|uncensored|assistant|vision) ;;
    image)
        echo "'image' is generated by ComfyUI, not Ollama — Ollama has no diffusion on Linux." >&2
        echo "Preload an image model with: modes/ai/setup/04-download-image-models.sh   (run it with: distro-ai-image)" >&2
        exit 1 ;;
    *) echo "Unknown use-case '$USECASE'. Try: coding cad day-to-day know-it-all uncensored assistant vision." >&2; exit 1 ;;
esac

command -v ollama >/dev/null 2>&1 || { echo "ollama CLI not found — run (sudo) modes/ai/setup/01-install-ollama.sh first." >&2; exit 1; }

# The pull is served by the ollama SYSTEM service (weights land in the service's
# store, /usr/share/ollama/.ollama, not your home), so this runs as your normal
# user — no sudo. Confirm the daemon is reachable so we fail with a useful hint
# instead of a raw connection error.
if ! ollama list >/dev/null 2>&1; then
    echo "Can't reach the Ollama daemon on ${OLLAMA_HOST:-127.0.0.1:11434}." >&2
    echo "Start it, then retry:  sudo systemctl restart ollama   (status: systemctl status ollama)" >&2
    exit 1
fi

# TIER -> ordered download classes, mirroring distro-ai-model's resolver: it
# tries the tier's preferred class first and falls back to the next class whose
# tag FITS the detected VRAM. The canonical model table only distinguishes a
# 'low' default (X1-class shared-memory laptop, 3B-8B) and a 'high' one (RTX
# 5090 / 32GB): cpu gets the smallest option, and mid stays on 'low' because a
# 32B Q4 (~20GB) doesn't fit a 16GB box comfortably.
#
# The ORDER (not just the first entry) matters: each tier is a VRAM *range*, so
# the preferred class does not always fit. This list is deliberately identical
# to the `base` order in distro-ai-model's resolve_usecase_model.
case "$TIER" in
    cpu)            CLASS_ORDER=(cpu low high) ;;
    entry|mid)      CLASS_ORDER=(low cpu high) ;;
    high|max|ultra) CLASS_ORDER=(high low cpu) ;;
esac

# (use-case, class) -> exact ollama.com tag + approx Q4 download size (GB) +
# min_vram_gb, from the canonical model table. Tags are pinned (never :latest)
# for reproducibility. know-it-all/uncensored/assistant have no <=3B variant, so
# cpu reuses the 8B 'low' tag (heavier on a CPU-only box, but there's no smaller
# one to offer).
#
# min_vram_gb MUST track distro-ai-model's "models" table: it is what that tool
# gates on, so a stale value here re-opens the double-download bug below. It is
# NOT the download size — a Q4 that downloads as 26GB wants 28GB resident.
model_for() {  # <usecase> <class> -> prints "<tag>\t<approx_gb>\t<min_vram_gb>"
    case "$1:$2" in
        coding:cpu|cad:cpu)   printf 'qwen2.5-coder:3b\t2\t3'     ;;
        coding:low|cad:low)   printf 'qwen2.5-coder:7b\t4.7\t6'   ;;
        coding:high|cad:high) printf 'qwen2.5-coder:32b\t20\t20'  ;;

        day-to-day:cpu)  printf 'gemma3:4b\t3.3\t4'   ;;
        day-to-day:low)  printf 'llama3.1:8b\t4.9\t6' ;;
        day-to-day:high) printf 'qwen3:32b\t20\t20'   ;;

        know-it-all:cpu|know-it-all:low) printf 'qwen3:8b\t5.2\t6'         ;;
        know-it-all:high)                printf 'deepseek-r1:32b\t20\t20'  ;;

        uncensored:cpu|uncensored:low) printf 'dolphin3:8b\t4.9\t6'           ;;
        uncensored:high)               printf 'dolphin-mixtral:8x7b\t26\t28'  ;;

        assistant:cpu|assistant:low) printf 'llama3.1:8b\t4.9\t6'             ;;
        assistant:high)              printf 'qwen3:30b-a3b-instruct\t18\t20'  ;;

        vision:cpu)  printf 'moondream:1.8b\t1.1\t2' ;;
        vision:low)  printf 'qwen2.5vl:7b\t6\t7'     ;;
        vision:high) printf 'qwen2.5vl:32b\t21\t21'  ;;
    esac
}

fits() {  # <min_vram_gb> -> true if it fits the detected VRAM (or VRAM unknown)
    [ "$VRAM_MIB" -gt 0 ] || return 0          # unknown -> don't gate (back-compat)
    # Drop any fractional part first: bash arithmetic is integer-only and would
    # abort the script on a float, the way the size column next to it allows.
    # distro-ai-model's load_model guards the same field the same way.
    local minv="${1%%.*}"
    [[ "$minv" =~ ^[0-9]+$ ]] || return 0      # unparseable -> don't gate
    [ "$(( minv * 1024 ))" -le "$VRAM_MIB" ]
}

# profile=efficiency mirrors distro-ai-model exactly: it ignores the tier's class
# order and ranks the use-case's tags by the table's min_vram_gb (ascending),
# then loads the lightest that fits. Every use-case here maps cpu/low/high with
# cpu<=low<=high, so re-sorting CLASS_ORDER by each class's min_vram_gb yields the
# same lightest-first order distro-ai-model's resolver computes. (balance/power
# leave CLASS_ORDER as the tier order above — no reorder.)
if [ "$PROFILE" = "efficiency" ]; then
    _ranked=()
    while IFS= read -r _c; do [ -n "$_c" ] && _ranked+=("$_c"); done < <(
        for class in "${CLASS_ORDER[@]}"; do
            # model_for prints "tag<TAB>size<TAB>min_vram_gb"; rank on min_vram_gb.
            IFS=$'\t' read -r _t _ _mv <<< "$(model_for "$USECASE" "$class")"
            [ -n "${_t:-}" ] && printf '%s\t%s\n' "${_mv%%.*}" "$class"
        done | sort -n -s -k1,1 | cut -f2
    )
    [ "${#_ranked[@]}" -gt 0 ] && CLASS_ORDER=("${_ranked[@]}")
fi

# Walk the tier's classes and preload the first tag that FITS — the same choice
# `distro-ai-model use` will make later. Skipping this gate is what made a 24GB
# 'high' box pull dolphin-mixtral:8x7b (~26GB, wants 28GB) only for
# distro-ai-model to reject it as too big and pull dolphin3:8b as a SECOND
# download. VRAM_MIB=0 (unknown) fits everything, so the tier's preferred class
# still wins and behaviour is unchanged from before the gate.
TAG=""; SIZE_GB=""; CLASS=""
FIRST_TAG=""; FIRST_SIZE=""; FIRST_MINV=""
for class in "${CLASS_ORDER[@]}"; do
    IFS=$'\t' read -r tag size minv <<< "$(model_for "$USECASE" "$class")"
    [ -n "${tag:-}" ] || continue              # this use-case has no tag for this class
    # Remember the preferred (first mapped) tag as the last-resort fallback.
    [ -n "$FIRST_TAG" ] || { FIRST_TAG="$tag"; FIRST_SIZE="$size"; FIRST_MINV="$minv"; }
    if fits "$minv"; then TAG="$tag"; SIZE_GB="$size"; CLASS="$class"; break; fi
done

if [ -z "$TAG" ] && [ -n "$FIRST_TAG" ]; then
    # Nothing fits (e.g. a cpu-tier box with a little VRAM). distro-ai-model
    # falls back to its first candidate and warns rather than refusing to run —
    # match that, or the two tools would again disagree on the tag.
    TAG="$FIRST_TAG"; SIZE_GB="$FIRST_SIZE"
    echo "WARNING: $TAG wants ~${FIRST_MINV}GB VRAM but only ~$(( VRAM_MIB / 1024 ))GB detected — Ollama will spill to system RAM (slow). No smaller variant exists for '$USECASE'." >&2
fi
[ -n "${TAG:-}" ] || { echo "No model mapped for use-case '$USECASE' at tier '$TIER'." >&2; exit 1; }

echo -e "\033[36mTier: $TIER   use-case: $USECASE   ->  $TAG\033[0m"
# Say so when the tier's preferred model was skipped, so the smaller download
# isn't mistaken for the wrong model being picked.
if [ -n "$CLASS" ] && [ "$CLASS" != "${CLASS_ORDER[0]}" ]; then
    echo "(~$(( VRAM_MIB / 1024 ))GB VRAM detected: the '${CLASS_ORDER[0]}' model for this tier doesn't fit, using the '$CLASS' one — same choice distro-ai-model will make.)"
fi
# Honest Ollama sizing: a 7-8B Q4 is ~4-5GB and a 32B ~20GB — nowhere near the
# "provision ~220GB" the old LM Studio 'pull everything' warning implied, because
# only this ONE model is fetched.
echo -e "\033[33mThis downloads ~${SIZE_GB} GB (one model). Make sure you have the disk + bandwidth.\033[0m"
[ "$USECASE" = "vision" ] && echo "Vision models pull their projector (mmproj) automatically — it's bundled in the tag."

echo -e "\033[36m\n== ollama pull $TAG ==\033[0m"
ollama pull "$TAG" || { echo "WARNING: 'ollama pull $TAG' failed — check the tag at ollama.com and that the daemon has network access." >&2; exit 1; }

echo -e "\033[32m\nDone — $TAG is downloaded (nothing loaded into VRAM yet).\033[0m"
echo "Load it, or switch use-cases later (each pulls its model on first use):"
echo "  distro-ai-model use $USECASE          # load what you just pulled"
echo "  distro-ai-model use coding|cad|day-to-day|know-it-all|uncensored|assistant|vision"
echo "Downloaded weights live in the ollama service store (/usr/share/ollama/.ollama) — never committed."
