#!/usr/bin/env bash
#
# Preloads ONE tier-matched local LLM for AI mode via `ollama pull`. Replaces the
# old LM Studio bulk `lms get` download. Image-generation models (FLUX/SDXL) are
# NOT here — those run in ComfyUI, see 04-download-image-models.sh.
#
# By default it pulls the *coding* model for the active hardware TIER — a single
# ~4-5GB 7B on a laptop, not 150GB of every model. Switching to another use-case
# later (`distro-ai-model use <case>`) pulls that model on demand, so there's no
# need to download them all up front.
#
# The tier comes from --tier, else $REFRACT_AI_TIER, else ~/.config/refract-ai/tier
# (written by distro-ai-detect-tier), else 'max'.
#
# Usage:
#   ./02-preload-models.sh                     # coding model for the active tier
#   ./02-preload-models.sh --tier entry        # coding model for the entry tier
#   ./02-preload-models.sh day-to-day          # a different use-case, active tier
#   ./02-preload-models.sh --tier high coding  # coding model for the high tier
#
# Use-cases: coding cad day-to-day know-it-all uncensored assistant vision
#            (image generation is ComfyUI — see distro-ai-image, not here).

set -euo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/refract-ai"

# --tier <t> may lead the args; otherwise fall back to env/config/default.
TIER=""
if [ "${1:-}" = "--tier" ]; then
    TIER="${2:-}"
    [ -n "$TIER" ] || { echo "--tier requires a tier name (cpu entry mid high max ultra)." >&2; exit 1; }
    shift 2   # safe: a non-empty $2 guarantees $# >= 2, so this never aborts under set -e
fi
[ -n "$TIER" ] || TIER="${REFRACT_AI_TIER:-$(cat "$CONFIG_HOME/tier" 2>/dev/null || echo max)}"
case "$TIER" in
    cpu|entry|mid|high|max|ultra) ;;
    *) echo "Unknown tier '$TIER' (cpu entry mid high max ultra)." >&2; exit 1 ;;
esac

# The use-case to preload (default: coding) — one positional arg after --tier.
USECASE="${1:-coding}"
case "$USECASE" in
    coding|cad|day-to-day|know-it-all|uncensored|assistant|vision) ;;
    image)
        echo "'image' is generated by ComfyUI, not Ollama — Ollama has no diffusion on Linux." >&2
        echo "Preload an image model with: modes/ai/setup/04-download-image-models.sh   (run it with: distro-ai-image)" >&2
        exit 1 ;;
    *) echo "Unknown use-case '$USECASE'. Try: coding cad day-to-day know-it-all uncensored assistant vision." >&2; exit 1 ;;
esac

command -v ollama >/dev/null 2>&1 || { echo "ollama CLI not found — run (sudo) modes/ai/setup/01-install-ollama.sh first." >&2; exit 1; }

# The pull is served by the ollama SYSTEM service (weights land in the service's
# store, /usr/share/ollama/.ollama, not your home), so this runs as your normal
# user — no sudo. Confirm the daemon is reachable so we fail with a useful hint
# instead of a raw connection error.
if ! ollama list >/dev/null 2>&1; then
    echo "Can't reach the Ollama daemon on ${OLLAMA_HOST:-127.0.0.1:11434}." >&2
    echo "Start it, then retry:  sudo systemctl restart ollama   (status: systemctl status ollama)" >&2
    exit 1
fi

# TIER -> download class. The canonical model table only distinguishes a 'low'
# default (X1-class shared-memory laptop, 3B-8B) and a 'high' one (RTX 5090 /
# 32GB): cpu gets the smallest option, and mid stays on 'low' because a 32B Q4
# (~20GB) doesn't fit a 16GB box comfortably.
case "$TIER" in
    cpu)            CLASS="cpu"  ;;
    entry|mid)      CLASS="low"  ;;
    high|max|ultra) CLASS="high" ;;
esac

# (use-case, class) -> exact ollama.com tag + approx Q4 download size (GB), from
# the canonical model table. Tags are pinned (never :latest) for reproducibility.
# know-it-all/uncensored/assistant have no <=3B variant, so cpu reuses the 8B
# 'low' tag (heavier on a CPU-only box, but there's no smaller one to offer).
model_for() {  # <usecase> <class> -> prints "<tag>\t<approx_gb>"
    case "$1:$2" in
        coding:cpu|cad:cpu)   printf 'qwen2.5-coder:3b\t2'    ;;
        coding:low|cad:low)   printf 'qwen2.5-coder:7b\t4.7'  ;;
        coding:high|cad:high) printf 'qwen2.5-coder:32b\t20'  ;;

        day-to-day:cpu)  printf 'gemma3:4b\t3.3'  ;;
        day-to-day:low)  printf 'llama3.1:8b\t4.9' ;;
        day-to-day:high) printf 'qwen3:32b\t20'   ;;

        know-it-all:cpu|know-it-all:low) printf 'qwen3:8b\t5.2'        ;;
        know-it-all:high)                printf 'deepseek-r1:32b\t20'  ;;

        uncensored:cpu|uncensored:low) printf 'dolphin3:8b\t4.9'          ;;
        uncensored:high)               printf 'dolphin-mixtral:8x7b\t26'  ;;

        assistant:cpu|assistant:low) printf 'llama3.1:8b\t4.9'             ;;
        assistant:high)              printf 'qwen3:30b-a3b-instruct\t18'   ;;

        vision:cpu)  printf 'moondream:1.8b\t1.1' ;;
        vision:low)  printf 'qwen2.5vl:7b\t6'     ;;
        vision:high) printf 'qwen2.5vl:32b\t21'   ;;
    esac
}

IFS=$'\t' read -r TAG SIZE_GB <<< "$(model_for "$USECASE" "$CLASS")"
[ -n "${TAG:-}" ] || { echo "No model mapped for use-case '$USECASE' at tier '$TIER'." >&2; exit 1; }

echo -e "\033[36mTier: $TIER   use-case: $USECASE   ->  $TAG\033[0m"
# Honest Ollama sizing: a 7-8B Q4 is ~4-5GB and a 32B ~20GB — nowhere near the
# "provision ~220GB" the old LM Studio 'pull everything' warning implied, because
# only this ONE model is fetched.
echo -e "\033[33mThis downloads ~${SIZE_GB} GB (one model). Make sure you have the disk + bandwidth.\033[0m"
[ "$USECASE" = "vision" ] && echo "Vision models pull their projector (mmproj) automatically — it's bundled in the tag."

echo -e "\033[36m\n== ollama pull $TAG ==\033[0m"
ollama pull "$TAG" || { echo "WARNING: 'ollama pull $TAG' failed — check the tag at ollama.com and that the daemon has network access." >&2; exit 1; }

echo -e "\033[32m\nDone — $TAG is downloaded (nothing loaded into VRAM yet).\033[0m"
echo "Load it, or switch use-cases later (each pulls its model on first use):"
echo "  distro-ai-model use $USECASE          # load what you just pulled"
echo "  distro-ai-model use coding|cad|day-to-day|know-it-all|uncensored|assistant|vision"
echo "Downloaded weights live in the ollama service store (/usr/share/ollama/.ollama) — never committed."
